version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8089:8080"
      -
  my-app:
    build: .
    depends_on:
      - wiremock
    environment:
      - WIREMOCK_URL=http://wiremock:8089